# Generated by Django 4.1.7 on 2023-06-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('precoporhora', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JogoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_diario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UtilizacaoConsoleCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.cliente')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.console')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.cliente')),
                ('jogo_plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.jogoplataforma')),
            ],
        ),
        migrations.AddField(
            model_name='jogoplataforma',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.plataforma'),
        ),
        migrations.CreateModel(
            name='ItemLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('jogo_plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.jogoplataforma')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.locacao')),
            ],
        ),
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos42.console')),
            ],
        ),
    ]
